version: "3.7"

services:
    db:
        image: postgres:12-alpine
        container_name: db
        env_file:
            - local.env
        volumes:
            - "./db/main:/var/lib/postgresql/data"
        ports:
            - "5432:5432"

#    backend:
#        image: backend
#        container_name: backend
#        env_file:
#            - local.env
#        build:
#            context: ./backend
#            dockerfile: Dockerfile
#        command: bash /gunicorn_run.sh
#        ports:
#            - "8000:8000"
#        volumes:
#            - ./backend/src:/app
#        depends_on:
#            - db
