version: "3.7"

services:
    db:
        image: postgres:12-alpine
        container_name: db
        env_file:
            - prod.env
        volumes:
            - "./db/main:/var/lib/postgresql/data"
        ports:
            - "5432:5432"

    backend:
        image: algol2302/options-and-pushes
        container_name: backend
        env_file:
            - prod.env
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: bash /gunicorn_run.sh
        ports:
            - "8000:8000"
        volumes:
            - ./data/media:/app/media
            - ./backend/src:/app
        depends_on:
            - db

    nginx:
        image: nginx:1.19-alpine
        container_name: nginx
        env_file:
            - prod.env
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ./data/media:/app/media:ro
            - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 80:80
        depends_on:
            - backend
