version: "3.7"

services:
    db:
        image: postgres:12-alpine
        container_name: db
        env_file:
            - local.env
        volumes:
            - "./db/main:/var/lib/postgresql/data"
        ports:
            - "5432:5432"
